name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        scala-version: [2.13.16]
        java-version: [11, 17]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Install sbt
      run: |
        curl -L -o sbt.deb https://github.com/sbt/sbt/releases/download/v1.9.8/sbt-1.9.8.deb
        sudo dpkg -i sbt.deb
        sudo apt-get update
        sudo apt-get install sbt
    
    - name: Cache SBT
      uses: actions/cache@v4
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', '**/project/build.properties', '**/project/Dependencies.scala') }}
        restore-keys: |
          ${{ runner.os }}-sbt-
    
    - name: Run tests
      run: sbt test
    
    - name: Check formatting
      run: sbt scalafmtCheckAll
      continue-on-error: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.java-version }}
        path: target/test-reports/
        retention-days: 7